"""
Django settings for siksha_setu project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os

load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-e#91+_*#8p5h4*jo=fgc-dw*4y&-8y#^-fl0-^dacnw*ge(7ba'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Payment Gateway Configuration
# Khalti ePayment API v2
KHALTI_PUBLIC_KEY = os.getenv('KHALTI_PUBLIC_KEY', '')
KHALTI_SECRET_KEY = os.getenv('KHALTI_SECRET_KEY', '')
KHALTI_INITIATE_URL = os.getenv('KHALTI_INITIATE_URL', 'https://a.khalti.com/api/v2/epayment/initiate/')
KHALTI_VERIFY_URL = os.getenv('KHALTI_VERIFY_URL', 'https://a.khalti.com/api/v2/epayment/lookup/')

# eSewa Configuration (RC/Test)
ESEWA_MERCHANT_CODE = os.getenv('ESEWA_MERCHANT_CODE') or 'EPAYTEST'
ESEWA_SECRET_KEY = os.getenv('ESEWA_SECRET_KEY') or '8gBm/:&EnhH.1/q'
ESEWA_FORM_URL = os.getenv('ESEWA_FORM_URL') or 'https://rc-epay.esewa.com.np/api/epay/main/v2/form'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Local apps
    'accounts',
    'courses',
    'payments',
    'reviews',
    'core',
    'adminpanel',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'accounts.middleware.AdminRedirectMiddleware',
]

# Quick Fix: Allow framing for certificate preview
X_FRAME_OPTIONS = 'SAMEORIGIN'


ROOT_URLCONF = 'siksha_setu.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'siksha_setu.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (User uploaded files)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
# https://docs.djangoproject.com/en/5.1/topics/auth/customizing/#substituting-a-custom-user-model

AUTH_USER_MODEL = 'accounts.CustomUser'

# Authentication Backend
# Custom backend to ensure only verified users can login
# Note: Only EmailBackend is used to enforce is_verified check
AUTHENTICATION_BACKENDS = [
    'accounts.backends.EmailBackend',
]

# Email Configuration
# https://docs.djangoproject.com/en/5.1/topics/email/

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = 'Siksha Setu <sikshasetu01@gmail.com>'
SERVER_EMAIL = 'sikshasetu01@gmail.com'

# Session Configuration
# https://docs.djangoproject.com/en/5.1/ref/settings/#sessions

SESSION_COOKIE_HTTPONLY = True  # Prevents JavaScript access to session cookie
SESSION_COOKIE_SECURE = False  # Set to True in production with HTTPS
SESSION_SAVE_EVERY_REQUEST = False  # Save session on every request (optional, increases security)
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # Session persists until expiration or logout
SESSION_COOKIE_AGE = 86400  # 24 hours in seconds

# Login URL & Redirects
LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = 'accounts:student_dashboard'

# Message Tags for Bootstrap
from django.contrib.messages import constants as messages
MESSAGE_TAGS = {
    messages.DEBUG: 'secondary',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'danger',
}
