# Generated by Django 5.1 on 2026-01-03 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_teacherprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='languages',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Languages'),
        ),
    ]
