# Generated by Django 5.1 on 2026-01-07 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_enrollment_is_paid_alter_lesson_youtube_video_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='mcq_score',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='overall_score',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='progress_percentage',
        ),
        migrations.RemoveField(
            model_name='lessonprogress',
            name='last_position',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='certificate_unlocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='completed_units',
            field=models.PositiveIntegerField(default=0, help_text='Number of fully watched videos'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='mastery_score',
            field=models.FloatField(default=0.0, help_text='(unit_progress * 0.6) + (quiz_score * 0.4)'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='quiz_score',
            field=models.FloatField(default=0.0, help_text='Average quiz performance (0-100)'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='unit_progress',
            field=models.FloatField(default=0.0, help_text='(completed_units / total_units) * 100'),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='max_position',
            field=models.PositiveIntegerField(default=0, help_text='Furthest position watched'),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='watch_time',
            field=models.PositiveIntegerField(default=0, help_text='Total cumulative watch time in seconds'),
        ),
    ]
