# Generated by Django 5.1 on 2026-01-08 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_enrollment_mcq_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='likes_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
