# Generated by Django 5.1 on 2026-01-30 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_likes_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonprogress',
            name='quiz_completed',
            field=models.BooleanField(default=False),
        ),
    ]
