# Generated by Django 5.1 on 2026-02-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_tag_course_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonprogress',
            name='watched_ranges',
            field=models.JSONField(blank=True, default=list, help_text='[[start, end]] unique segments'),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='watch_time',
            field=models.PositiveIntegerField(default=0, help_text='Total unique covered seconds'),
        ),
    ]
