# Generated by Django 5.1 on 2026-02-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_lessonprogress_watched_ranges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonprogress',
            name='quiz_unlocked',
            field=models.BooleanField(default=False),
        ),
    ]
