# Generated by Django 5.1 on 2026-04-02 11:09

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_lessonprogress_quiz_unlocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=courses.models.get_unique_filename),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=courses.models.get_unique_filename),
        ),
        migrations.AlterField(
            model_name='lessonresource',
            name='file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=courses.models.get_unique_filename),
        ),
    ]
