# Generated by Django 5.1 on 2026-04-04 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_course_thumbnail_alter_lesson_video_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonprogress',
            name='is_unlocked',
            field=models.BooleanField(default=False, help_text='Lesson is accessible (persistent)'),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='Video criteria met (95% watch)'),
        ),
    ]
